### ISSUE TITLE
Interaction with use.model.frame=FALSE

### ISSUE THREAD

**Issue by markseeto** [hongooi73/glmnetUtils#29]
Thanks for the glmnetUtils package. I haven't used it much yet, but it looks very useful. I'm using version 1.1.8.

Consider the following example:

```
set.seed(1)

d <- data.frame(x1 = factor(rep(c("A", "B", "C"), each = 20)),
                x2 = rnorm(60),
                y = rnorm(60))

g <- glmnet(y ~ x1*x2, data = d, alpha = 0)

rownames(coef(g))

## [1] "(Intercept)" "x1A"         "x1B"         "x1C"         "x2"          "x1B:x2"      "x1C:x2"

```
Since we have terms `x1A`, `x1B` and `x1C`, I expected that there would also be an `x1A:x2` term. If we're including the interaction, does it make sense to have `x1A` without `x1A:x2`?

Also, is some sort of constraint used when we have `x1A`, `x1B` and `x1C` as well as the intercept? I fitted the model `y ~ x1 + x2` and I thought the `x1A`, `x1B` and `x1C` coefficient estimates might be constrained to sum to 0, but the sum wasn't quite zero (it was about 1e-5).

Thanks.

**Comment by hongooi73** [comment]
Hi, thanks for using the package.

glmnetUtils uses `model.matrix` to generate the matrix of coefficients for each additive term in the formula (ie, the terms that are separated by a `+`). So in this case, the matrix is obtained by a call to

```r
model.matrix(~0 + x1*x2, data=d)
```

which gives the result you're seeing. The x1A:x2 term is unnecessary because it's aliased to x2 and x1A. If you want it, you can run

```r
glmnet(y ~ x1 + x2 + x1:x2, ...)
```

which forces the interaction term to be built independently of the main effects.

There is no explicit constraint on x1A/B/C when fitting regularised regression. A constraint is required for normal (unregularised) regression to make the model identifiable, but the shrinkage penalty makes that unnecessary here.

**Comment by markseeto** [comment]
Thanks for the explanation @hongooi73.

I hope it's OK if I ask a couple more questions.

In the vignette, you wrote:

> Another issue with the standard R approach is the treatment of factors. Normally, model.matrix will turn an N-level factor into an indicator matrix with N−1 columns, with one column being dropped. This is necessary for unregularised models as fit with lm and glm, since the full set of N columns is linearly dependent. With the usual treatment contrasts, the interpretation is that the dropped column represents a baseline level, while the coefficients for the other columns represent the difference in the response relative to the baseline.
> 
> This may not be appropriate for a regularised model as fit with glmnet. The regularisation procedure shrinks the coefficients towards zero, which forces the estimated differences from the baseline to be smaller. But this only makes sense if the baseline level was chosen beforehand, or is otherwise meaningful as a default; otherwise it is effectively making the levels more similar to an arbitrarily chosen level.

Are you sure about this? When I first read it, I agreed with it, but now I'm having doubts about "it is effectively making the levels more similar to an arbitrarily chosen level". The reason that I now doubt this is that I think the intercept estimate would also be adjusted, so that the predicted values for the categories would all be shrunk towards the mean.

A simple example:

```
library(glmnet)

set.seed(1)

d <- data.frame(x1 = factor(rep(c("A", "B", "C"), each = 20), levels = c("A", "B", "C")),
                x2 = factor(rep(c("A", "B", "C"), each = 20), levels = c("B", "A", "C")))

d$y <- 1*(d$x1 == "A") + 2*(d$x1 == "B") + 6*(d$x1 == "C") + rnorm(nrow(d), 0, 0.5)

mean(d$y)

## [1] 3.053808

M1 <- model.matrix(~ x1, data = d)[, -1]
M2 <- model.matrix(~ x2, data = d)[, -1]

g1 <- glmnet(M1, d$y, alpha = 0)
g2 <- glmnet(M2, d$y, alpha = 0)

coef(g1, s = 0)

##                     1
## (Intercept) 1.4127389
## x1B         0.5486251
## x1C         4.3745827

coef(g2, s = 0)

##                     1
## (Intercept)  2.168112
## x2A         -1.007879
## x2C          3.664966

coef(g1, s = 1000)

##                        1
## (Intercept)  3.051649324
## x1B         -0.003480643
## x1C          0.009957237

coef(g2, s = 1000)

##                        1
## (Intercept)  3.052643031
## x2A         -0.006458482
## x2C          0.009953954
```
So `g1` and `g2` both shrink the averages for the 3 categories towards the mean. Or am I missing your point?

Also, does the problem you describe disappear if "sum" contrasts are used instead of "treatment" contrasts?

**Comment by hongooi73** [comment]
That could probably be better worded, but the issue is that if you omit the dummy variable, the predictions for `x1 == A` become a weird combination of the overall mean, and the effect for that level. This in turn affects all the other levels, because the mean of the predictions is still constrained to be equal to the mean of the response. Eg compare to a model with all dummy variables included:

```r
M01 <- model.matrix(~ 0 + x1, data=d)
g01 <- glmnet(M01, d$y, alpha=0)

d$p1 <- predict(g1, M1, s=g1$lambda[length(g1$lambda)])
d$p01 <- predict(g01, M01, s=g01$lambda[length(g01$lambda)])

library(dplyr)
d %>%
    group_by(x1) %>%
    summarise(y=mean(y), p1=mean(p1), p01=mean(p01))
```
```
# A tibble: 3 x 4
  x1        y    p1   p01
* <fct> <dbl> <dbl> <dbl>
1 A      1.10  1.41  1.21
2 B      2.00  1.96  2.06
3 C      6.07  5.79  5.89
```

So the predictions for `x1 == A` are inflated, while those for `x1 == C` are reduced, when you omit one dummy variable. I'll admit I'm not an expert on how regularised regression works though, you may also want to ask Trevor Hastie about this.

**Comment by markseeto** [comment]
Thanks for the explanation and example @hongooi73. I now agree with you that the usual parameterisation with treatment contrasts is not ideal in this situation, although I'm still not 100% sure.

What helped to convince me was to compare `plot(g1)` to `plot(g01)`. As far as I can tell, using `contr.sum` instead of `contr.treatment` is another way to solve the problem.

Thanks for your help.
